apiVersion: apps/v1
kind: Deployment
metadata:
  name: k7api-deployment
spec:
  selector:
    matchLabels:
      app: k7api-pod
  template:
    metadata:
      labels:
        app: k7api-pod
    spec:
      containers:
      - name: k7api-container
        image: k7api:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: k7api-service
spec:
  type: LoadBalancer
  selector:
    app: k7api-pod
  ports:
  - port: 58080
    targetPort: 80